schema/postgres/360$rule.commission.sql
schema/postgres/360$rule.fee.sql
schema/postgres/360$rule.limit.sql
schema/postgres/750$rule.decision.fetch.sql
schema/postgres/750$rule.rule.fetch.sql

swap all money types with numeric and add rule.rule.fetch function

fix: swap all money types with numeric and add rule.rule.fetch function

---

ui/react/components/ActionDialog/index.js
ui/react/components/Dialog/index.js

Can you please check this code and merge if it is ok!

Style changes

---

api/postgre/schema/350$rule.condition.sql
api/postgre/schema/750$rule.decision.fetch.sql
api/postgre/schema/750$rule.rule.add.sql
api/postgre/schema/750$rule.rule.edit.sql
api/sql/schema/350$rule.condition.sql
api/sql/schema/750$rule.decision.fetch.sql
api/sql/schema/750$rule.decision.lookup.sql
api/sql/schema/750$rule.rule.add.sql
api/sql/schema/750$rule.rule.edit.sql
ui/react/components/Dialog/Section/Destination/index.js
ui/react/components/Dialog/Section/Source/index.js
ui/react/components/Dialog/index.js
ui/react/pages/Main/index.js

* remove sourceProductId and add SourceCardProductId and sourceAccountProductId
* remove destinationProductId and add destinationAccountProductId

feat: card and account products

---

ui/react/components/Dialog/Section/Splits/index.js

Please note that this is fix to stop blocking front-end. The data that getTagData function returns should come from db. @ChrispCode @krasimirkostadinow please consider this idea and if you approve it make a refactor.

fix: add additional tags in frontend

---

api/script/index.js

fix: don't override  by reference

---

ui/react/components/Dialog/Section/Channel/RoleOption.js
ui/react/components/Dialog/Section/Channel/index.js
ui/react/components/Dialog/Section/Channel/style.css
ui/react/components/Dialog/index.js
ui/react/pages/Main/index.js

Added trimming to dialog inputs.
Rules without condition actors will now appear (impl)
Condition actor roles are no longer limited to agent types, rather they include all roles. (part impl)
Rules with deleted condition actors will appear and gray out legacy roles.

fix: MCTUNE-5347

---

api/sql/schema/750$rule.rule.fetch.sql
ui/react/components/Dialog/Section/Limit/index.js
ui/react/components/Dialog/index.js
ui/react/components/Dialog/validations.js
ui/react/components/Grid/index.js

1) change the priority sort order from desc to asc
2) add validations for daily, weekly and monthly transaction amount and count
3) mark priority field as mandatory

fix: rule screen issues

---

ui/react/pages/Main/index.js
ui/react/pages/Main/style.css

1) change action bar position, it should be sticky and align the action buttons by right align

fix: UTP-175

---

common/index.js
ui/react/pages/RuleProfile/Tabs/defaultState.js

Adding / editing rule without setting limit values results in zeroes

fix: default null instead of empty string

---

ui/react/components/Dialog/Section/Limit/index.js
ui/react/components/Dialog/Section/Splits/Assignment/index.js
ui/react/components/Dialog/Section/Splits/Cumulative/Range/index.js
ui/react/components/Dialog/Section/Splits/Cumulative/index.js

fix(UA-78): Money values formatting

---

errors.js

fix-ABTN-3400

---

ui/react/pages/Main/index.js

- Add condition for sending removed rule data to the notification API

fix(ABTN-3833):[ABZ] System Alerts: Tags are missing in the sent email for Rule delete event

---

package.json
ui/react/components/Grid/index.js
ui/react/components/Grid/style.css
ui/react/pages/RuleProfile/Tabs/style.css
ui/react/pages/Rules/index.js
ui/react/pages/Rules/style.css

DEPENDS ON: https://github.com/softwaregroup-bg/ut-front-react/pull/521

refactor: frontend

---

ui/react/pages/Main/reducer.js

- Remove 3 values from operation list used for operation filtering

fix(UATCIB-150): [MAP][ALM-191]Daily limit amount rule is not working

---

validations/rule/rule.add.js
validations/rule/rule.edit.js

added joi validation for currency in rule.add and rule.edit

fix(CEM-4383): Rules modules is accepting USD for currency

---

common/index.js
ui/react/pages/Rules/index.js

- make 0 value visible for the required startAmount field
- fix delete rule functionality

fix (UTM-85): fix front end issues in rule tab

---

validations/index.js
validations/rule/rule.rule.fetchDeleted.js

- Add fetchDeleted method to API

fix (MSA-428): Http error displayed when viewing deleted rules

---

index.js
package.json
test/steps/index.js
test/steps/steps.rule.js
test/steps/steps.utils.js

@venetahristova Please review.

test: UTCORE-140 Add utils file

---

api/sql/schema/750-rule.decision.fetch.sql
api/sql/schema/750-rule.decision.lookup.sql
errors.js
validations/decision/rule.decision.fetch.js
validations/decision/rule.decision.lookup.js

depends on https://git.softwaregroup.com/ut5/ut-transfer/merge_requests/242

fix(MSA-2182): edit amount type rounding is not correct

---

common/index.js
package.json
ui/react/pages/RuleProfile/Tabs/Destination/index.js
ui/react/pages/RuleProfile/Tabs/Source/index.js

Signed-off-by: francis.kinuthia <francis.kinuthia@softwaregroup.com>

fix(Agent management) fix Business units not displayed on save NMB-1567

---

README.md
api/sql/schema/340-rule.limitOutOpData.sql
api/sql/schema/350-rule.conditionOutOp.sql
api/sql/schema/350-rule.limitOutOp.sql
api/sql/schema/351-rule.conditionActorOutOp.sql
api/sql/schema/750-rule.ruleOutOp.save.sql
validations/index.js
validations/rule/rule.ruleOutOp.save.js

ut-rule changes to add outlet and operator limits for agency nmb project needs

---

test/jobs/test.rule.js
test/steps/steps.utils.js

@venetahristova, @lambrevalora, please review

test: UTCORE-448: add rule cases

---

test/jobs/test.rule.js

hasStrict array sorting matters

test: hasStrict array sorting matters
